# Copyright 2016, 2017 Peter Dimov
# Copyright 2018 Joh Maddock
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

python: "2.7"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop
    - /feature\/.*/

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=11
      osx_image: xcode7.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=14,1z
      osx_image: xcode7.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=03
      osx_image: xcode8.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=11
      osx_image: xcode8.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=14,1z
      osx_image: xcode8.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=03
      osx_image: xcode9.4.1

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=11
      osx_image: xcode9.4.1

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=14,1z
      osx_image: xcode9.4.1


install:
  - BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/boost_install
  - git submodule update --init libs/headers
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/graph
  - python tools/boostdep/depinst/depinst.py graph
  - ./bootstrap.sh
  - ./b2 headers


script:
  - |-
    echo "using $TOOLSET : : $COMPILER ;" > ~/user-config.jam
  - IFS=','
  - for CXXLOCAL in $CXXSTD; do  (cd libs/config/test && ../../../b2 config_info_travis_install toolset=$TOOLSET cxxstd=$CXXLOCAL && ./config_info_travis && rm ./config_info_travis)  done
  - unset IFS
  - ./b2 -j3 libs/graph/test toolset=$TOOLSET cxxstd=$CXXSTD

notifications:
  email:
    on_success: always
